# Generated by Django 4.2.6 on 2023-11-18 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('segundoNombre', models.CharField(blank=True, default='', max_length=50, verbose_name='Segundo Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('segundoApellido', models.CharField(blank=True, default='', max_length=50, verbose_name='Segundo Apellido')),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('ocupacion', models.CharField(default='No tiene', max_length=100)),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=10)),
                ('estado_civil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], default='No tiene', max_length=20)),
                ('mujer_embarazada', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2)),
                ('mujer_lactancia', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2)),
                ('discapacidad', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_medicamentos', models.CharField(blank=True, max_length=100, null=True)),
                ('habitante_encamada', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2)),
                ('carnet_patria', models.CharField(blank=True, max_length=20, null=True)),
                ('vota', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2)),
                ('centro_votacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JefeFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_casa', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Rancho', 'Rancho'), ('Anexo', 'Anexo'), ('Otro', 'Otro')], max_length=100, verbose_name='Tipo de Vivienda')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('numeroCasa', models.PositiveIntegerField(verbose_name='Numero de Casa')),
                ('numeroCalle', models.PositiveIntegerField(verbose_name='Numero de calle')),
                ('Habitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='censo.habitante')),
            ],
        ),
        migrations.AddConstraint(
            model_name='habitante',
            constraint=models.UniqueConstraint(condition=models.Q(('cedula__isnull', False)), fields=('cedula',), name='unique_cedula'),
        ),
        migrations.AddField(
            model_name='cargafamiliar',
            name='Habitante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='censo.habitante'),
        ),
        migrations.AddField(
            model_name='cargafamiliar',
            name='jefe_familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.jefefamiliar'),
        ),
    ]
