# Generated by Django 4.2.6 on 2023-11-28 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0004_cargafamiliar_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitante',
            name='cedula',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], default='Soltero', max_length=20),
        ),
        migrations.AlterField(
            model_name='jefefamiliar',
            name='numeroCalle',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Numero de calle'),
        ),
        migrations.AlterField(
            model_name='jefefamiliar',
            name='numeroCasa',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Numero de Casa'),
        ),
    ]
